project_id = "bcjuejipotipblxsfrfr"

[functions.notify-new-lead]
verify_jwt = false

[functions.submit-lead]
verify_jwt = false

[functions.get-recaptcha-config]
verify_jwt = false

[functions.scrape-company]
verify_jwt = false

[functions.research-lead]
verify_jwt = false

[functions.notify-new-intake]
verify_jwt = false

[functions.submit-intake]
verify_jwt = false

[functions.verify-intake-password]
verify_jwt = false

[functions.get-signed-urls]
verify_jwt = false

[functions.upload-intake-asset]
verify_jwt = false
